#Sources
source = ~/.config/hypr/controls/keybinds.conf
source = ~/.config/hypr/controls/autostart.conf
source = ~/.config/hypr/controls/looks.conf
source = ~/.config/hypr/controls/workspaces.conf
source = ~/.config/hypr/controls/input.conf
source = ~/.config/hypr/controls/envi.conf
source = ~/.config/hypr/controls/permissions.conf
source = ~/.config/hypr/controls/monitors.conf


