exec-once = hyprpaper -c ~/.config/hypr/others/hyprpaper.conf
exec-once = waybar &
exec-once = systemctl enable --now bluetooth
exec-once = systemctl enable --now NetworkManager
exec-once = /usr/lib/polkit-kde-authentication-agent-1
